# Generated by Django 4.0.3 on 2022-03-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='User_Face',
        ),
    ]
