# Generated by Django 4.0.3 on 2022-03-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_rename_hero_user_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_face',
            name='age',
            field=models.CharField(default='10', max_length=60),
        ),
        migrations.AddField(
            model_name='user_face',
            name='gender',
            field=models.CharField(default='A', max_length=3),
        ),
        migrations.AddField(
            model_name='user_face',
            name='mobile',
            field=models.CharField(default='000000', max_length=15),
        ),
        migrations.AddField(
            model_name='user_face',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
