# Generated by Django 4.0.3 on 2022-03-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alter_user_face_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_face',
            name='password',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
